baseURL = 'https://ryota-nakanishi-dev.github.io/'
relativeURLs = true
defaultContentLanguage = 'ja'
locale = 'ja'
title = ''
theme = 'mainroad'


# トップページ下部に記事一覧を出さない設定
mainSections = []

[author]
  name = 'Ryota Nakanishi'
  bio = '芝浦工業大学大学院 理工学研究科 システム理工学専攻 修士課程2年'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 10

  [[menu.main]]
    identifier = 'news'
    name = 'News'
    url = '/news/'
    weight = 15

  [[menu.main]]
    identifier = 'research'
    name = 'Research'
    url = '/research/'
    weight = 20

  [[menu.main]]
    identifier = 'publications'
    name = 'Publications'
    url = '/publications/'
    weight = 30

[params]
  customCSS = ["css/custom.css"]
  subtitle = ''
  description = '芝浦工業大学川上研究室（フルードパワーシステム研究室）所属の修士課程2年'
  highlightColor = "#002147"

  readmore = false

  # 見出しの変更設定
  [params.messages]
    recent_title = "最近のお知らせ・研究活動"

  [params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["news"]